language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

env:
  global:
  - TMPDIR=/tmp

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli
  - yarn global add coveralls

script:
  - ng lint expenses-web
  - ng test expenses-web --watch=false --browsers=ChromeHeadless --code-coverage
  - ng build expenses-web --prod

after_success:
  - cat coverage/lcov.info | coveralls
  - bash scripts/gh-pages.sh $TMPDIR/gh-pages $TRAVIS_BUILD_DIR/dist/expenses-web
